[2022-11-27T18:05:02.737+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v01.task1 manual__2022-11-26T21:12:41.625385+00:00 [queued]>
[2022-11-27T18:05:02.761+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v01.task1 manual__2022-11-26T21:12:41.625385+00:00 [queued]>
[2022-11-27T18:05:02.761+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-27T18:05:02.761+0000] {taskinstance.py:1363} INFO - Starting attempt 6 of 6
[2022-11-27T18:05:02.761+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-27T18:05:02.859+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): task1> on 2022-11-26 21:12:41.625385+00:00
[2022-11-27T18:05:02.869+0000] {standard_task_runner.py:55} INFO - Started process 210 to run task
[2022-11-27T18:05:02.874+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v01', 'task1', 'manual__2022-11-26T21:12:41.625385+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmp8g3ck8dk']
[2022-11-27T18:05:02.880+0000] {standard_task_runner.py:83} INFO - Job 76: Subtask task1
[2022-11-27T18:05:03.103+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_with_catchup_backfill_v01.task1 manual__2022-11-26T21:12:41.625385+00:00 [running]> on host 9f4316afb24b
[2022-11-27T18:05:03.295+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bruno
AIRFLOW_CTX_DAG_ID=dag_with_catchup_backfill_v01
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-11-26T21:12:41.625385+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-26T21:12:41.625385+00:00
[2022-11-27T18:05:03.296+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-27T18:05:03.297+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'Echo This is a simple bash command!']
[2022-11-27T18:05:03.324+0000] {subprocess.py:86} INFO - Output:
[2022-11-27T18:05:03.331+0000] {subprocess.py:93} INFO - /bin/bash: line 1: Echo: command not found
[2022-11-27T18:05:03.332+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-11-27T18:05:03.348+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-27T18:05:03.352+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=dag_with_catchup_backfill_v01, task_id=task1, execution_date=20221126T211241, start_date=20221127T180502, end_date=20221127T180503
[2022-11-27T18:05:03.387+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 76 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 210)
[2022-11-27T18:05:03.418+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-27T18:05:03.448+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
