[2022-11-30T01:32:33.565+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v01.task1 scheduled__2022-11-28T00:00:00+00:00 [queued]>
[2022-11-30T01:32:33.757+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v01.task1 scheduled__2022-11-28T00:00:00+00:00 [queued]>
[2022-11-30T01:32:33.757+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T01:32:33.757+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 6
[2022-11-30T01:32:33.757+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T01:32:33.968+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): task1> on 2022-11-28 00:00:00+00:00
[2022-11-30T01:32:34.019+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v01', 'task1', 'scheduled__2022-11-28T00:00:00+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpz3o139qm']
[2022-11-30T01:32:34.020+0000] {standard_task_runner.py:83} INFO - Job 120: Subtask task1
[2022-11-30T01:32:33.972+0000] {standard_task_runner.py:55} INFO - Started process 231 to run task
[2022-11-30T01:32:34.766+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_with_catchup_backfill_v01.task1 scheduled__2022-11-28T00:00:00+00:00 [running]> on host 2c9b3e546def
[2022-11-30T01:32:35.521+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bruno
AIRFLOW_CTX_DAG_ID=dag_with_catchup_backfill_v01
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T00:00:00+00:00
[2022-11-30T01:32:35.523+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-30T01:32:35.523+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'Echo This is a simple bash command!']
[2022-11-30T01:32:35.612+0000] {subprocess.py:86} INFO - Output:
[2022-11-30T01:32:35.661+0000] {subprocess.py:93} INFO - /bin/bash: line 1: Echo: command not found
[2022-11-30T01:32:35.665+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-11-30T01:32:35.716+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-30T01:32:35.720+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_catchup_backfill_v01, task_id=task1, execution_date=20221128T000000, start_date=20221130T013233, end_date=20221130T013235
[2022-11-30T01:32:35.794+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 120 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 231)
[2022-11-30T01:32:35.856+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-30T01:32:35.901+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
