[2022-11-28T02:20:59.144+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-27T00:00:00+00:00 [queued]>
[2022-11-28T02:20:59.179+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-27T00:00:00+00:00 [queued]>
[2022-11-28T02:20:59.180+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-28T02:20:59.180+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 6
[2022-11-28T02:20:59.180+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-28T02:20:59.231+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-11-27 00:00:00+00:00
[2022-11-28T02:20:59.259+0000] {standard_task_runner.py:55} INFO - Started process 1944 to run task
[2022-11-28T02:20:59.276+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'scheduled__2022-11-27T00:00:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp3oze3xpa']
[2022-11-28T02:20:59.278+0000] {standard_task_runner.py:83} INFO - Job 107: Subtask create_postgres_table
[2022-11-28T02:20:59.439+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-27T00:00:00+00:00 [running]> on host 04d264156372
[2022-11-28T02:20:59.557+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bruno Lima
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v01
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-27T00:00:00+00:00
[2022-11-28T02:20:59.569+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-11-28T02:20:59.571+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 115, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.internal" to address: Temporary failure in name resolution

[2022-11-28T02:20:59.579+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20221127T000000, start_date=20221128T022059, end_date=20221128T022059
[2022-11-28T02:20:59.607+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 107 for task create_postgres_table (could not translate host name "host.docker.internal" to address: Temporary failure in name resolution
; 1944)
[2022-11-28T02:20:59.655+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-28T02:20:59.679+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-30T01:34:13.070+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-27T00:00:00+00:00 [queued]>
[2022-11-30T01:34:13.116+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-27T00:00:00+00:00 [queued]>
[2022-11-30T01:34:13.117+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T01:34:13.117+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 6
[2022-11-30T01:34:13.117+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T01:34:13.217+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-11-27 00:00:00+00:00
[2022-11-30T01:34:13.224+0000] {standard_task_runner.py:55} INFO - Started process 425 to run task
[2022-11-30T01:34:13.256+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'scheduled__2022-11-27T00:00:00+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmppaik1eak']
[2022-11-30T01:34:13.262+0000] {standard_task_runner.py:83} INFO - Job 136: Subtask create_postgres_table
[2022-11-30T01:34:13.573+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-27T00:00:00+00:00 [running]> on host 2c9b3e546def
[2022-11-30T01:34:13.808+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bruno Lima
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v01
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-27T00:00:00+00:00
[2022-11-30T01:34:13.836+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-11-30T01:34:13.843+0000] {sql.py:315} INFO - Running statement: 
            create table if not exists dag_runs(
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        , parameters: None
[2022-11-30T01:34:13.853+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(dag_runs, 2200) already exists.

[2022-11-30T01:34:13.864+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20221127T000000, start_date=20221130T013413, end_date=20221130T013413
[2022-11-30T01:34:13.895+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 136 for task create_postgres_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(dag_runs, 2200) already exists.
; 425)
[2022-11-30T01:34:13.972+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-30T01:34:14.028+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
