[2022-11-26T21:27:39.295+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v01.task1 scheduled__2022-11-25T00:00:00+00:00 [queued]>
[2022-11-26T21:27:39.306+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_backfill_v01.task1 scheduled__2022-11-25T00:00:00+00:00 [queued]>
[2022-11-26T21:27:39.306+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-26T21:27:39.306+0000] {taskinstance.py:1363} INFO - Starting attempt 4 of 6
[2022-11-26T21:27:39.306+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-26T21:27:39.325+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): task1> on 2022-11-25 00:00:00+00:00
[2022-11-26T21:27:39.330+0000] {standard_task_runner.py:55} INFO - Started process 8283 to run task
[2022-11-26T21:27:39.332+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v01', 'task1', 'scheduled__2022-11-25T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmphcgihblg']
[2022-11-26T21:27:39.334+0000] {standard_task_runner.py:83} INFO - Job 40: Subtask task1
[2022-11-26T21:27:39.403+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_with_catchup_backfill_v01.task1 scheduled__2022-11-25T00:00:00+00:00 [running]> on host 3d834fabdefd
[2022-11-26T21:27:39.497+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bruno
AIRFLOW_CTX_DAG_ID=dag_with_catchup_backfill_v01
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-11-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-25T00:00:00+00:00
[2022-11-26T21:27:39.498+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-26T21:27:39.498+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'Echo This is a simple bash command!']
[2022-11-26T21:27:39.522+0000] {subprocess.py:86} INFO - Output:
[2022-11-26T21:27:39.523+0000] {subprocess.py:93} INFO - /bin/bash: line 1: Echo: command not found
[2022-11-26T21:27:39.524+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-11-26T21:27:39.536+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-26T21:27:39.540+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_catchup_backfill_v01, task_id=task1, execution_date=20221125T000000, start_date=20221126T212739, end_date=20221126T212739
[2022-11-26T21:27:39.554+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 40 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 8283)
[2022-11-26T21:27:39.584+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-26T21:27:39.600+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
