[2022-11-26T20:22:00.032+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v04.greet scheduled__2022-11-25T00:00:00+00:00 [queued]>
[2022-11-26T20:22:00.045+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v04.greet scheduled__2022-11-25T00:00:00+00:00 [queued]>
[2022-11-26T20:22:00.045+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-26T20:22:00.046+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 6
[2022-11-26T20:22:00.046+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-26T20:22:00.063+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): greet> on 2022-11-25 00:00:00+00:00
[2022-11-26T20:22:00.067+0000] {standard_task_runner.py:55} INFO - Started process 2125 to run task
[2022-11-26T20:22:00.069+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v04', 'greet', 'scheduled__2022-11-25T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmp_1tqn4zf']
[2022-11-26T20:22:00.071+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask greet
[2022-11-26T20:22:00.141+0000] {task_command.py:376} INFO - Running <TaskInstance: our_dag_with_python_operator_v04.greet scheduled__2022-11-25T00:00:00+00:00 [running]> on host 3d834fabdefd
[2022-11-26T20:22:00.229+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=burno
AIRFLOW_CTX_DAG_ID=our_dag_with_python_operator_v04
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2022-11-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-25T00:00:00+00:00
[2022-11-26T20:22:00.230+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 14, in greet
    name = ti.xcom_pull(task_id='get_name')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'task_id'
[2022-11-26T20:22:00.238+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v04, task_id=greet, execution_date=20221125T000000, start_date=20221126T202200, end_date=20221126T202200
[2022-11-26T20:22:00.253+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 7 for task greet (xcom_pull() got an unexpected keyword argument 'task_id'; 2125)
[2022-11-26T20:22:00.287+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-26T20:22:00.307+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
