[2022-11-27T18:41:23.755+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-26T00:00:00+00:00 [queued]>
[2022-11-27T18:41:23.768+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-26T00:00:00+00:00 [queued]>
[2022-11-27T18:41:23.768+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-27T18:41:23.768+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 6
[2022-11-27T18:41:23.769+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-27T18:41:23.785+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-11-26 00:00:00+00:00
[2022-11-27T18:41:23.790+0000] {standard_task_runner.py:55} INFO - Started process 376 to run task
[2022-11-27T18:41:23.793+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'scheduled__2022-11-26T00:00:00+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpgf22jx3j']
[2022-11-27T18:41:23.794+0000] {standard_task_runner.py:83} INFO - Job 95: Subtask create_postgres_table
[2022-11-27T18:41:23.848+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-26T00:00:00+00:00 [running]> on host 04d264156372
[2022-11-27T18:41:23.924+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bruno Lima
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v01
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-26T00:00:00+00:00
[2022-11-27T18:41:23.932+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-11-27T18:41:23.955+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 115, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.interval" to address: Name or service not known

[2022-11-27T18:41:23.966+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20221126T000000, start_date=20221127T184123, end_date=20221127T184123
[2022-11-27T18:41:23.979+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 95 for task create_postgres_table (could not translate host name "host.docker.interval" to address: Name or service not known
; 376)
[2022-11-27T18:41:24.004+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-27T18:41:24.041+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-27T18:50:36.256+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-26T00:00:00+00:00 [queued]>
[2022-11-27T18:50:36.267+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-26T00:00:00+00:00 [queued]>
[2022-11-27T18:50:36.267+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-27T18:50:36.267+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 6
[2022-11-27T18:50:36.267+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-27T18:50:36.283+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-11-26 00:00:00+00:00
[2022-11-27T18:50:36.289+0000] {standard_task_runner.py:55} INFO - Started process 1355 to run task
[2022-11-27T18:50:36.292+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'scheduled__2022-11-26T00:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpjok11mgf']
[2022-11-27T18:50:36.293+0000] {standard_task_runner.py:83} INFO - Job 100: Subtask create_postgres_table
[2022-11-27T18:50:36.350+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-26T00:00:00+00:00 [running]> on host 04d264156372
[2022-11-27T18:50:36.432+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bruno Lima
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v01
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-26T00:00:00+00:00
[2022-11-27T18:50:36.443+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-11-27T18:50:36.456+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 115, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.internal" to address: Name or service not known

[2022-11-27T18:50:36.470+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20221126T000000, start_date=20221127T185036, end_date=20221127T185036
[2022-11-27T18:50:36.494+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 100 for task create_postgres_table (could not translate host name "host.docker.internal" to address: Name or service not known
; 1355)
[2022-11-27T18:50:36.543+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-27T18:50:36.580+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-30T01:39:14.921+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-26T00:00:00+00:00 [queued]>
[2022-11-30T01:39:14.936+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-26T00:00:00+00:00 [queued]>
[2022-11-30T01:39:14.936+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T01:39:14.936+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 6
[2022-11-30T01:39:14.937+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T01:39:14.956+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-11-26 00:00:00+00:00
[2022-11-30T01:39:14.962+0000] {standard_task_runner.py:55} INFO - Started process 972 to run task
[2022-11-30T01:39:14.964+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'scheduled__2022-11-26T00:00:00+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpy8adq5v0']
[2022-11-30T01:39:14.965+0000] {standard_task_runner.py:83} INFO - Job 143: Subtask create_postgres_table
[2022-11-30T01:39:15.057+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-26T00:00:00+00:00 [running]> on host 2c9b3e546def
[2022-11-30T01:39:15.170+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bruno Lima
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v01
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-26T00:00:00+00:00
[2022-11-30T01:39:15.187+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-11-30T01:39:15.190+0000] {sql.py:315} INFO - Running statement: 
            create table if not exists dag_runs(
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        , parameters: None
[2022-11-30T01:39:15.191+0000] {postgres.py:96} INFO - NOTICE:  relation "dag_runs" already exists, skipping

[2022-11-30T01:39:15.202+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20221126T000000, start_date=20221130T013914, end_date=20221130T013915
[2022-11-30T01:39:15.259+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-11-30T01:39:15.285+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
